import { Platform, StyleSheet } from 'react-native';
import { palette, radii, shadows, spacing } from '../../shared/ui/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, minHeight: Platform.OS === 'web' ? '100vh' : undefined, backgroundColor: palette.page, color: palette.text },
  topBar: { minHeight: 76, paddingHorizontal: spacing[6], flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: palette.line },
  brandLockup: { flexDirection: 'row', alignItems: 'center', gap: spacing[3] },
  brandMarkSmall: { width: 38, height: 38, borderRadius: 14, backgroundColor: palette.lime, alignItems: 'center', justifyContent: 'center' },
  brandMarkText: { color: palette.ink, fontSize: 24, fontWeight: '900', fontStyle: 'italic' },
  brandName: { color: palette.text, fontSize: 17, letterSpacing: -0.5, fontWeight: '800' },
  brandCaption: { color: palette.textFaint, fontSize: 9, letterSpacing: 1.7, marginTop: 3, fontWeight: '700' },
  topBarRight: { flexDirection: 'row', alignItems: 'center', gap: spacing[3] },
  headerAvatar: { width: 40, height: 40, borderRadius: 15, backgroundColor: palette.surfaceRaised, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: palette.line, fontSize: 20 },
  dashboardLayout: { flex: 1, flexDirection: 'row', padding: spacing[4], gap: spacing[4], minHeight: 0 },
  dashboardLayoutMobile: { flexDirection: 'column', padding: spacing[3], gap: spacing[3] },
  dashboardLayoutCompact: { gap: 8 },
  mapPanel: { flex: 1, minWidth: 0, borderRadius: radii.xl, overflow: 'hidden', position: 'relative', backgroundColor: palette.mapFallback, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  mapPanelMobile: { flex: 1.08, minHeight: 240, borderRadius: radii.lg },
  mapPanelCompact: { flex: 0.76, minHeight: 180 },
  map: { flex: 1, width: '100%', height: '100%' },
  mapPlaceholder: { ...StyleSheet.absoluteFillObject, overflow: 'hidden', backgroundColor: '#17201C' },
  placeholderRoad: { position: 'absolute', height: 1, backgroundColor: 'rgba(196,216,184,0.12)' },
  placeholderRoadOne: { width: '145%', left: '-20%', top: '26%', transform: [{ rotate: '-17deg' }] },
  placeholderRoadTwo: { width: '145%', left: '-18%', top: '55%', transform: [{ rotate: '13deg' }] },
  placeholderRoadThree: { width: '125%', left: '-8%', top: '74%', transform: [{ rotate: '-7deg' }] },
  placeholderRoadFour: { width: '110%', left: '-4%', top: '42%', transform: [{ rotate: '61deg' }] },
  placeholderRoute: { position: 'absolute', width: 150, height: 150, borderRadius: 75, borderWidth: 1, borderStyle: 'dashed', borderColor: 'rgba(206,255,87,0.22)', left: '50%', top: '43%', marginLeft: -75, marginTop: -75 },
  placeholderSignalOuter: { position: 'absolute', width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(206,255,87,0.07)', left: '50%', top: '43%', marginLeft: -32, marginTop: -32 },
  placeholderSignalInner: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.lime, borderWidth: 3, borderColor: '#111713' },
  placeholderSignalIcon: { color: palette.ink, fontSize: 20, fontWeight: '800' },
  mapTopOverlay: { position: 'absolute', top: spacing[5], left: spacing[5], right: spacing[5], flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  mapTitleCard: { paddingHorizontal: 15, paddingVertical: 12, borderRadius: radii.md, backgroundColor: palette.overlay, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  mapTitleEyebrow: { color: palette.lime, fontSize: 9, fontWeight: '800', letterSpacing: 1.5, marginBottom: 4 },
  mapTitle: { color: palette.text, fontSize: 16, fontWeight: '800', letterSpacing: -0.4 },
  iconButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: palette.overlay, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  iconButtonText: { color: palette.text, fontSize: 24, fontWeight: '700' },
  locateButton: { width: 48, height: 48 },
  mapBottomOverlay: { position: 'absolute', left: spacing[5], right: spacing[5], bottom: spacing[4], alignItems: 'flex-start' },
  locationPrompt: { padding: 13, backgroundColor: palette.overlay, borderRadius: radii.md, borderWidth: 1, borderColor: palette.line, flexDirection: 'row', alignItems: 'center', gap: 11, ...shadows.panel },
  locationPromptIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: palette.limeWash, alignItems: 'center', justifyContent: 'center', color: palette.lime, fontSize: 21 },
  locationPromptCopy: { gap: 3 },
  locationPromptTitle: { color: palette.text, fontWeight: '800', fontSize: 12 },
  locationPromptText: { color: palette.textMuted, fontSize: 11 },
  locationPromptArrow: { color: palette.lime, fontSize: 17, fontWeight: '700', marginLeft: 8 },
  radiusCard: { paddingHorizontal: 16, paddingVertical: 14, backgroundColor: palette.overlay, borderRadius: radii.md, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  radiusHeader: { flexDirection: 'row', gap: 16, alignItems: 'center' },
  radiusEyebrow: { color: palette.textFaint, fontSize: 9, letterSpacing: 1.2, fontWeight: '800' },
  radiusValue: { color: palette.text, fontSize: 17, fontWeight: '800', marginTop: 3 },
  radiusOptions: { flexDirection: 'row', gap: 5 },
  radiusOption: { backgroundColor: palette.surfaceRaised, borderRadius: radii.pill, paddingHorizontal: 9, paddingVertical: 7 },
  radiusOptionActive: { backgroundColor: palette.lime },
  radiusOptionText: { fontSize: 10, fontWeight: '700', color: palette.textMuted },
  radiusOptionTextActive: { color: palette.ink },
  mapAttribution: { color: 'rgba(255,255,255,0.62)', fontSize: 8, letterSpacing: 1, marginTop: 10, marginLeft: 2 },
  pressed: { opacity: 0.82 },
  disabled: { opacity: 0.66 },

});
