import { Platform, StyleSheet } from 'react-native';
import { palette, radii, shadows, spacing } from '../../shared/ui/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, minHeight: Platform.OS === 'web' ? '100vh' : undefined, backgroundColor: palette.page, color: palette.text },
  topBar: { minHeight: 76, paddingHorizontal: spacing[6], flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: palette.line },
  brandLockup: { flexDirection: 'row', alignItems: 'center', gap: spacing[3] },
  brandMarkSmall: { width: 38, height: 38, borderRadius: 14, backgroundColor: palette.lime, alignItems: 'center', justifyContent: 'center' },
  brandMarkText: { color: palette.ink, fontSize: 24, fontWeight: '900', fontStyle: 'italic' },
  brandName: { color: palette.text, fontSize: 17, letterSpacing: -0.5, fontWeight: '800' },
  brandCaption: { color: palette.textFaint, fontSize: 9, letterSpacing: 1.7, marginTop: 3, fontWeight: '700' },
  topBarRight: { flexDirection: 'row', alignItems: 'center', gap: spacing[3] },
  headerAvatar: { width: 40, height: 40, borderRadius: 15, backgroundColor: palette.surfaceRaised, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: palette.line, fontSize: 20 },
  statusPill: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: radii.pill, backgroundColor: palette.surfaceRaised, flexDirection: 'row', alignItems: 'center', gap: 7 },
  statusPillLive: { backgroundColor: palette.limeWash },
  statusPillWarning: { backgroundColor: palette.surfaceRaised },
  statusPillText: { color: palette.textMuted, fontSize: 11, fontWeight: '700' },
  statusPillTextLive: { color: palette.lime },
  statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: palette.lime },
  dashboardLayout: { flex: 1, flexDirection: 'row', padding: spacing[4], gap: spacing[4], minHeight: 0 },
  dashboardLayoutMobile: { flexDirection: 'column', padding: spacing[3], gap: spacing[3] },
  mapPanel: { flex: 1, minWidth: 0, borderRadius: radii.xl, overflow: 'hidden', position: 'relative', backgroundColor: palette.mapFallback, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  mapPanelMobile: { flex: 1.08, minHeight: 270, borderRadius: radii.lg },
  map: { flex: 1, width: '100%', height: '100%' },
  mapTopOverlay: { position: 'absolute', top: spacing[5], left: spacing[5], right: spacing[5], flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  mapTitleCard: { paddingHorizontal: 15, paddingVertical: 12, borderRadius: radii.md, backgroundColor: palette.overlay, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  mapTitleEyebrow: { color: palette.lime, fontSize: 9, fontWeight: '800', letterSpacing: 1.5, marginBottom: 4 },
  mapTitle: { color: palette.text, fontSize: 16, fontWeight: '800', letterSpacing: -0.4 },
  iconButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: palette.overlay, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  iconButtonText: { color: palette.text, fontSize: 24, fontWeight: '700' },
  locateButton: { width: 48, height: 48 },
  mapBottomOverlay: { position: 'absolute', left: spacing[5], right: spacing[5], bottom: spacing[4], alignItems: 'flex-start' },
  locationPrompt: { padding: 13, backgroundColor: palette.overlay, borderRadius: radii.md, borderWidth: 1, borderColor: palette.line, flexDirection: 'row', alignItems: 'center', gap: 11, ...shadows.panel },
  locationPromptIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: palette.limeWash, alignItems: 'center', justifyContent: 'center', color: palette.lime, fontSize: 21 },
  locationPromptCopy: { gap: 3 },
  locationPromptTitle: { color: palette.text, fontWeight: '800', fontSize: 12 },
  locationPromptText: { color: palette.textMuted, fontSize: 11 },
  locationPromptArrow: { color: palette.lime, fontSize: 17, fontWeight: '700', marginLeft: 8 },
  radiusCard: { paddingHorizontal: 16, paddingVertical: 14, backgroundColor: palette.overlay, borderRadius: radii.md, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  radiusHeader: { flexDirection: 'row', gap: 16, alignItems: 'center' },
  radiusEyebrow: { color: palette.textFaint, fontSize: 9, letterSpacing: 1.2, fontWeight: '800' },
  radiusValue: { color: palette.text, fontSize: 17, fontWeight: '800', marginTop: 3 },
  radiusOptions: { flexDirection: 'row', gap: 5 },
  radiusOption: { backgroundColor: palette.surfaceRaised, borderRadius: radii.pill, paddingHorizontal: 9, paddingVertical: 7 },
  radiusOptionActive: { backgroundColor: palette.lime },
  radiusOptionText: { fontSize: 10, fontWeight: '700', color: palette.textMuted },
  radiusOptionTextActive: { color: palette.ink },
  mapAttribution: { color: 'rgba(255,255,255,0.62)', fontSize: 8, letterSpacing: 1, marginTop: 10, marginLeft: 2 },
  sidebar: { backgroundColor: palette.surface, borderRadius: radii.xl, borderWidth: 1, borderColor: palette.line, padding: spacing[5], overflow: 'hidden' },
  sidebarWide: { width: 352, flexShrink: 0 },
  sidebarMobile: { flex: 0.92, minHeight: 260, padding: spacing[4], borderRadius: radii.lg },
  sidebarHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing[4] },
  sectionEyebrow: { color: palette.textFaint, fontWeight: '800', letterSpacing: 1.5, fontSize: 9, marginBottom: 6 },
  sidebarTitle: { color: palette.text, fontSize: 20, fontWeight: '800', letterSpacing: -0.7 },
  countBadge: { backgroundColor: palette.surfaceRaised, paddingHorizontal: 10, paddingVertical: 6, borderRadius: radii.pill },
  countBadgeText: { color: palette.textMuted, fontSize: 11, fontWeight: '800' },
  onAirCard: { flexDirection: 'row', alignItems: 'center', padding: 13, backgroundColor: palette.limeWash, borderWidth: 1, borderColor: 'rgba(206,255,87,0.17)', borderRadius: radii.md, gap: 11, marginBottom: spacing[5] },
  onAirIcon: { width: 42, height: 42, borderRadius: 15, backgroundColor: 'rgba(206,255,87,0.12)', alignItems: 'center', justifyContent: 'center' },
  onAirIconText: { fontSize: 21, color: palette.lime },
  onAirCopy: { flex: 1 },
  onAirEyebrow: { color: palette.lime, letterSpacing: 1.05, fontSize: 8, fontWeight: '800', marginBottom: 4 },
  onAirName: { color: palette.text, fontSize: 13, fontWeight: '800' },
  onAirSignal: { width: 22, height: 22, borderRadius: 11, backgroundColor: 'rgba(206,255,87,0.17)', alignItems: 'center', justifyContent: 'center' },
  onAirSignalWaiting: { backgroundColor: 'rgba(255,255,255,0.1)' },
  onAirSignalDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: palette.lime },
  feedHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 9 },
  feedTitle: { color: palette.textMuted, fontSize: 11, fontWeight: '800' },
  feedScroll: { flex: 1, minHeight: 0 },
  feedList: { gap: 8, paddingBottom: 6, flexGrow: 1 },
  messageCard: { minHeight: 62, paddingHorizontal: 10, paddingVertical: 9, backgroundColor: palette.surfaceRaised, borderRadius: radii.md, borderWidth: 1, borderColor: palette.line, flexDirection: 'row', alignItems: 'center', gap: 10 },
  messageCardPlaying: { borderColor: 'rgba(206,255,87,0.52)', backgroundColor: palette.limeWash },
  messageAvatar: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.surface, borderRadius: 14, fontSize: 19 },
  messageCopy: { flex: 1, minWidth: 0 },
  messageName: { color: palette.text, fontSize: 12, fontWeight: '800' },
  messageMeta: { color: palette.textFaint, fontSize: 10, marginTop: 4 },
  playButton: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: palette.surface, color: palette.textMuted },
  playButtonActive: { backgroundColor: palette.lime },
  playButtonText: { color: palette.text, fontSize: 12, fontWeight: '900' },
  emptyState: { flex: 1, minHeight: 96, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 20 },
  emptyIcon: { color: palette.textFaint, fontSize: 28, marginBottom: 5 },
  emptyTitle: { color: palette.text, fontSize: 12, fontWeight: '800' },
  emptyCopy: { color: palette.textFaint, fontSize: 10, marginTop: 4, textAlign: 'center' },
  talkArea: { alignItems: 'center', paddingVertical: 13, borderTopWidth: 1, borderTopColor: palette.line, marginTop: 5 },
  talkButton: { width: 70, height: 70, borderRadius: 26, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.lime, shadowColor: palette.lime, shadowOpacity: 0.21, shadowRadius: 20, shadowOffset: { width: 0, height: 5 }, elevation: 6 },
  talkButtonRecording: { backgroundColor: palette.record, transform: [{ scale: 1.06 }] },
  talkButtonPressed: { transform: [{ scale: 0.96 }] },
  talkButtonBlocked: { backgroundColor: palette.surfaceRaised, shadowOpacity: 0 },
  talkButtonIcon: { color: palette.ink, fontSize: 27, fontWeight: '900' },
  talkTitle: { color: palette.text, fontSize: 13, fontWeight: '800', marginTop: 9 },
  talkHint: { color: palette.textFaint, fontSize: 10, marginTop: 3 },
  sidebarFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 12, borderTopWidth: 1, borderTopColor: palette.line },
  footerUser: { flexDirection: 'row', alignItems: 'center', gap: 9, flex: 1 },
  footerAvatar: { width: 34, height: 34, borderRadius: 12, backgroundColor: palette.surfaceRaised, alignItems: 'center', justifyContent: 'center', fontSize: 17 },
  footerUserCopy: { flex: 1 },
  footerUserName: { color: palette.text, fontSize: 11, fontWeight: '800' },
  footerStatus: { color: palette.textFaint, fontSize: 9, marginTop: 3 },
  profileMenuButton: { width: 34, height: 34, borderRadius: 12, backgroundColor: palette.surfaceRaised, alignItems: 'center', justifyContent: 'center' },
  profileMenuButtonText: { color: palette.textMuted, fontSize: 21, lineHeight: 24, fontWeight: '900' },
  inlineError: { color: palette.warning, fontSize: 10, lineHeight: 14, paddingBottom: 8 },
  pressed: { opacity: 0.82 },

});
