import { StyleSheet } from 'react-native';
import { palette, radii, spacing } from '../../../shared/ui/tokens';

export const sidebarStyles = StyleSheet.create({
  sidebar: { backgroundColor: palette.surface, borderRadius: radii.xl, borderWidth: 1, borderColor: palette.line, padding: spacing[5], overflow: 'hidden' },
  sidebarWide: { width: 352, flexShrink: 0 },
  sidebarMobile: { flex: 0.92, minHeight: 220, padding: spacing[4], borderRadius: radii.lg },
  sidebarCompact: { flex: 1.24, padding: spacing[3] },
  sidebarHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing[4] },
  sectionEyebrow: { color: palette.textFaint, fontWeight: '800', letterSpacing: 1.5, fontSize: 9, marginBottom: 6 },
  sidebarTitle: { color: palette.text, fontSize: 20, fontWeight: '800', letterSpacing: -0.7 },
  countBadge: { backgroundColor: palette.surfaceRaised, paddingHorizontal: 10, paddingVertical: 6, borderRadius: radii.pill },
  countBadgeText: { color: palette.textMuted, fontSize: 11, fontWeight: '800' },
  onAirCard: { flexDirection: 'row', alignItems: 'center', padding: 13, backgroundColor: palette.limeWash, borderWidth: 1, borderColor: 'rgba(206,255,87,0.17)', borderRadius: radii.md, gap: 11, marginBottom: spacing[5] },
  onAirIcon: { width: 42, height: 42, borderRadius: 15, backgroundColor: 'rgba(206,255,87,0.12)', alignItems: 'center', justifyContent: 'center' },
  onAirIconText: { fontSize: 21, color: palette.lime },
  onAirCopy: { flex: 1 },
  onAirEyebrow: { color: palette.lime, letterSpacing: 1.05, fontSize: 8, fontWeight: '800', marginBottom: 4 },
  onAirName: { color: palette.text, fontSize: 13, fontWeight: '800' },
  onAirSignal: { width: 22, height: 22, borderRadius: 11, backgroundColor: 'rgba(206,255,87,0.17)', alignItems: 'center', justifyContent: 'center' },
  onAirSignalWaiting: { backgroundColor: 'rgba(255,255,255,0.1)' },
  onAirSignalDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: palette.lime },
  feedHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 9 },
  feedTitle: { color: palette.textMuted, fontSize: 11, fontWeight: '800' },
  feedScroll: { flex: 1, minHeight: 0 },
  feedList: { gap: 8, paddingBottom: 6, flexGrow: 1 },
  emptyState: { flex: 1, minHeight: 96, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 20 },
  emptyIcon: { color: palette.textFaint, fontSize: 28, marginBottom: 5 },
  emptyTitle: { color: palette.text, fontSize: 12, fontWeight: '800' },
  emptyCopy: { color: palette.textFaint, fontSize: 10, marginTop: 4, textAlign: 'center' },
  sidebarFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 12, borderTopWidth: 1, borderTopColor: palette.line },
  footerUser: { flexDirection: 'row', alignItems: 'center', gap: 9, flex: 1 },
  footerAvatar: { width: 34, height: 34, borderRadius: 12, backgroundColor: palette.surfaceRaised, alignItems: 'center', justifyContent: 'center', fontSize: 17 },
  footerUserCopy: { flex: 1 },
  footerUserName: { color: palette.text, fontSize: 11, fontWeight: '800' },
  footerStatus: { color: palette.textFaint, fontSize: 9, marginTop: 3 },
  profileMenuButton: { width: 34, height: 34, borderRadius: 12, backgroundColor: palette.surfaceRaised, alignItems: 'center', justifyContent: 'center' },
  profileMenuButtonText: { color: palette.textMuted, fontSize: 21, lineHeight: 24, fontWeight: '900' },
  inlineError: { color: palette.warning, fontSize: 10, lineHeight: 14, paddingBottom: 8 },
});
