import { StyleSheet } from 'react-native';
import { palette, radii, shadows, spacing } from '../../../shared/ui/tokens';

export const mapPanelStyles = StyleSheet.create({
  panel: { flex: 1, minWidth: 0, borderRadius: radii.xl, overflow: 'hidden', position: 'relative', backgroundColor: palette.mapFallback, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  panelMobile: { flex: 1.08, minHeight: 240, borderRadius: radii.lg },
  panelCompact: { flex: 0.76, minHeight: 180 },
  map: { flex: 1, width: '100%', height: '100%' },
  placeholder: { ...StyleSheet.absoluteFillObject, overflow: 'hidden', backgroundColor: '#17201C' },
  placeholderRoad: { position: 'absolute', height: 1, backgroundColor: 'rgba(196,216,184,0.12)' },
  placeholderRoadOne: { width: '145%', left: '-20%', top: '26%', transform: [{ rotate: '-17deg' }] },
  placeholderRoadTwo: { width: '145%', left: '-18%', top: '55%', transform: [{ rotate: '13deg' }] },
  placeholderRoadThree: { width: '125%', left: '-8%', top: '74%', transform: [{ rotate: '-7deg' }] },
  placeholderRoadFour: { width: '110%', left: '-4%', top: '42%', transform: [{ rotate: '61deg' }] },
  placeholderRoute: { position: 'absolute', width: 150, height: 150, borderRadius: 75, borderWidth: 1, borderStyle: 'dashed', borderColor: 'rgba(206,255,87,0.22)', left: '50%', top: '43%', marginLeft: -75, marginTop: -75 },
  placeholderSignalOuter: { position: 'absolute', width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(206,255,87,0.07)', left: '50%', top: '43%', marginLeft: -32, marginTop: -32 },
  placeholderSignalInner: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.lime, borderWidth: 3, borderColor: '#111713' },
  placeholderSignalIcon: { color: palette.ink, fontSize: 20, fontWeight: '800' },
  topOverlay: { position: 'absolute', top: spacing[5], left: spacing[5], right: spacing[5], flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  titleCard: { paddingHorizontal: 15, paddingVertical: 12, borderRadius: radii.md, backgroundColor: palette.overlay, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  titleEyebrow: { color: palette.lime, fontSize: 9, fontWeight: '800', letterSpacing: 1.5, marginBottom: 4 },
  title: { color: palette.text, fontSize: 16, fontWeight: '800', letterSpacing: -0.4 },
  iconButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: palette.overlay, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  iconButtonText: { color: palette.text, fontSize: 24, fontWeight: '700' },
  locateButton: { width: 48, height: 48 },
  bottomOverlay: { position: 'absolute', left: spacing[5], right: spacing[5], bottom: spacing[4], alignItems: 'flex-start' },
  locationPrompt: { padding: 13, backgroundColor: palette.overlay, borderRadius: radii.md, borderWidth: 1, borderColor: palette.line, flexDirection: 'row', alignItems: 'center', gap: 11, ...shadows.panel },
  locationPromptIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: palette.limeWash, alignItems: 'center', justifyContent: 'center', color: palette.lime, fontSize: 21 },
  locationPromptCopy: { gap: 3 },
  locationPromptTitle: { color: palette.text, fontWeight: '800', fontSize: 12 },
  locationPromptText: { color: palette.textMuted, fontSize: 11 },
  locationPromptArrow: { color: palette.lime, fontSize: 17, fontWeight: '700', marginLeft: 8 },
  radiusCard: { paddingHorizontal: 16, paddingVertical: 14, backgroundColor: palette.overlay, borderRadius: radii.md, borderWidth: 1, borderColor: palette.line, ...shadows.panel },
  radiusHeader: { flexDirection: 'row', gap: 16, alignItems: 'center' },
  radiusEyebrow: { color: palette.textFaint, fontSize: 9, letterSpacing: 1.2, fontWeight: '800' },
  radiusValue: { color: palette.text, fontSize: 17, fontWeight: '800', marginTop: 3 },
  radiusOptions: { flexDirection: 'row', gap: 5 },
  radiusOption: { backgroundColor: palette.surfaceRaised, borderRadius: radii.pill, paddingHorizontal: 9, paddingVertical: 7 },
  radiusOptionActive: { backgroundColor: palette.lime },
  radiusOptionText: { fontSize: 10, fontWeight: '700', color: palette.textMuted },
  radiusOptionTextActive: { color: palette.ink },
  attribution: { color: 'rgba(255,255,255,0.62)', fontSize: 8, letterSpacing: 1, marginTop: 10, marginLeft: 2 },
  pressed: { opacity: 0.82 },
  disabled: { opacity: 0.66 },
});
